name: 'NewRelic AI Agent (OpenAI)'
description: 'Automatically generate NewRelic observability for PR changes using OpenAI'
author: 'Your Team'
branding:
  icon: 'activity'
  color: 'green'

inputs:
  openai-api-key:
    description: 'OpenAI API key'
    required: true
  newrelic-api-key:
    description: 'NewRelic API key'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.2'
        
    - name: Install dependencies
      shell: bash
      run: |
        cd ${{ github.action_path }}
        bundle install
        
    - name: Run OpenAI Agent
      shell: bash
      env:
        OPENAI_API_KEY: ${{ inputs.openai-api-key }}
        NEWRELIC_API_KEY: ${{ inputs.newrelic-api-key }}
        GITHUB_TOKEN: ${{ github.token }}
        PR_NUMBER: ${{ github.event.pull_request.number }}
        GITHUB_REPOSITORY: ${{ github.repository }}
      run: |
        cd ${{ github.action_path }}
        ruby codepulse.rb
