# Updated workflow with on-demand trigger
# Copy this to your target repository at: .github/workflows/newrelic-ai.yml

name: NewRelic AI Analysis

on:
  issue_comment:
    types: [created]

# Required permissions
permissions:
  contents: read
  pull-requests: write

jobs:
  analyze:
    # Only run on PR comments containing the trigger phrase
    if: |
      github.event.issue.pull_request &&
      contains(github.event.comment.body, 'Constant Vigilance')
    
    runs-on: ubuntu-latest
    name: Analyze PR for Observability
    
    steps:
      - name: React to trigger comment
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.reactions.createForIssueComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              comment_id: context.payload.comment.id,
              content: 'eyes'
            });
            
            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: '🤖 **NewRelic AI Agent Starting...**\n\nAnalyzing PR for observability requirements. This may take 1-2 minutes.'
            });
      
      - name: Checkout PR branch
        uses: actions/checkout@v4
        with:
          ref: refs/pull/${{ github.event.issue.number }}/head
      
      - name: Checkout Action Repository
        uses: actions/checkout@v4
        with:
          repository: indrajitmb/newrelic-ai-agent-action
          ref: main
          path: .github/actions/newrelic-agent
      
      - name: Run NewRelic AI Agent
        uses: ./.github/actions/newrelic-agent
        with:
          openai-api-key: ${{ secrets.OPENAI_API_KEY }}
          newrelic-api-key: ${{ secrets.NEWRELIC_API_KEY }}
        env:
          PR_NUMBER: ${{ github.event.issue.number }}
          GITHUB_REPOSITORY: ${{ github.repository }}

# ============================================================
# Alternative Trigger Phrases (Optional)
# ============================================================
# You can add multiple trigger phrases by modifying the condition:
# 
# if: |
#   github.event.issue.pull_request && (
#     contains(github.event.comment.body, 'Constant Vigilance') ||
#     contains(github.event.comment.body, '/analyze-observability') ||
#     contains(github.event.comment.body, '/check-monitoring')
#   )

# ============================================================
# Setup Instructions
# ============================================================
# 1. Add secrets in repository settings:
#    - OPENAI_API_KEY
#    - NEWRELIC_API_KEY
#
# 2. Update line 36 with your action repository
#
# 3. To trigger: Comment "Constant Vigilance" on any PR
#
# 4. The action will:
#    - React with 👀 emoji
#    - Post "Starting..." message
#    - Run full analysis
#    - Post comprehensive results
