# Example workflow file
# Copy this to any microservice at: .github/workflows/newrelic-ai.yml

name: NewRelic AI Analysis

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  analyze:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      pull-requests: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch full history for better diff analysis
      
      - name: Run NewRelic AI Agent
        uses: your-org/newrelic-ai-agent-action@main  # Change to your org
        with:
          claude-api-key: ${{ secrets.CLAUDE_API_KEY }}
          newrelic-api-key: ${{ secrets.NEW_RELIC_API_KEY }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          pr-number: ${{ github.event.pull_request.number }}

# Optional: Run only on specific file changes
# on:
#   pull_request:
#     types: [opened, synchronize, reopened]
#     paths:
#       - 'app/**'
#       - 'lib/**'
#       - 'config/**'
#       # Add paths you want to monitor

# Optional: Skip draft PRs
# jobs:
#   analyze:
#     if: github.event.pull_request.draft == false
